// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: notify.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotifyStatus int32

const (
	SendNotifyStatus_SUCCESS SendNotifyStatus = 0 // 发送成功
	SendNotifyStatus_FAILED  SendNotifyStatus = 1 // 发送失败
)

// Enum value maps for SendNotifyStatus.
var (
	SendNotifyStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	SendNotifyStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x SendNotifyStatus) Enum() *SendNotifyStatus {
	p := new(SendNotifyStatus)
	*p = x
	return p
}

func (x SendNotifyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendNotifyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[0].Descriptor()
}

func (SendNotifyStatus) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[0]
}

func (x SendNotifyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendNotifyStatus.Descriptor instead.
func (SendNotifyStatus) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

// 获取wsid请求参数
type GetWsidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 业务系统用户登录Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWsidRequest) Reset() {
	*x = GetWsidRequest{}
	mi := &file_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWsidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWsidRequest) ProtoMessage() {}

func (x *GetWsidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWsidRequest.ProtoReflect.Descriptor instead.
func (*GetWsidRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (x *GetWsidRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取wsid响应参数
type GetWsidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wsid          string                 `protobuf:"bytes,1,opt,name=wsid,proto3" json:"wsid,omitempty"` // WS服务生成的唯一WebSocket连接ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWsidResponse) Reset() {
	*x = GetWsidResponse{}
	mi := &file_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWsidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWsidResponse) ProtoMessage() {}

func (x *GetWsidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWsidResponse.ProtoReflect.Descriptor instead.
func (*GetWsidResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (x *GetWsidResponse) GetWsid() string {
	if x != nil {
		return x.Wsid
	}
	return ""
}

// 发送通知请求参数
type SendNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wsid          []string               `protobuf:"bytes,1,rep,name=wsid,proto3" json:"wsid,omitempty"`       // 指定要发送的wsid数组
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 发送的消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotifyRequest) Reset() {
	*x = SendNotifyRequest{}
	mi := &file_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotifyRequest) ProtoMessage() {}

func (x *SendNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotifyRequest.ProtoReflect.Descriptor instead.
func (*SendNotifyRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotifyRequest) GetWsid() []string {
	if x != nil {
		return x.Wsid
	}
	return nil
}

func (x *SendNotifyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送通知响应参数
type SendNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SendNotifyStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=SendNotifyStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotifyResponse) Reset() {
	*x = SendNotifyResponse{}
	mi := &file_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotifyResponse) ProtoMessage() {}

func (x *SendNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotifyResponse.ProtoReflect.Descriptor instead.
func (*SendNotifyResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotifyResponse) GetStatus() SendNotifyStatus {
	if x != nil {
		return x.Status
	}
	return SendNotifyStatus_SUCCESS
}

var File_notify_proto protoreflect.FileDescriptor

const file_notify_proto_rawDesc = "" +
	"\n" +
	"\fnotify.proto\"&\n" +
	"\x0eGetWsidRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\x0fGetWsidResponse\x12\x12\n" +
	"\x04wsid\x18\x01 \x01(\tR\x04wsid\"A\n" +
	"\x11SendNotifyRequest\x12\x12\n" +
	"\x04wsid\x18\x01 \x03(\tR\x04wsid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x12SendNotifyResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.SendNotifyStatusR\x06status*+\n" +
	"\x10SendNotifyStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012q\n" +
	"\x06Notify\x12.\n" +
	"\aGetWsid\x12\x0f.GetWsidRequest\x1a\x10.GetWsidResponse\"\x00\x127\n" +
	"\n" +
	"SendNotify\x12\x12.SendNotifyRequest\x1a\x13.SendNotifyResponse\"\x00B\n" +
	"Z\b.;notifyb\x06proto3"

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData []byte
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)))
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notify_proto_goTypes = []any{
	(SendNotifyStatus)(0),      // 0: SendNotifyStatus
	(*GetWsidRequest)(nil),     // 1: GetWsidRequest
	(*GetWsidResponse)(nil),    // 2: GetWsidResponse
	(*SendNotifyRequest)(nil),  // 3: SendNotifyRequest
	(*SendNotifyResponse)(nil), // 4: SendNotifyResponse
}
var file_notify_proto_depIdxs = []int32{
	0, // 0: SendNotifyResponse.status:type_name -> SendNotifyStatus
	1, // 1: Notify.GetWsid:input_type -> GetWsidRequest
	3, // 2: Notify.SendNotify:input_type -> SendNotifyRequest
	2, // 3: Notify.GetWsid:output_type -> GetWsidResponse
	4, // 4: Notify.SendNotify:output_type -> SendNotifyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		EnumInfos:         file_notify_proto_enumTypes,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
