// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative notify.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: wsserver.proto

package wsserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WsServer_Preconnect_FullMethodName = "/WsServer/Preconnect"
	WsServer_Send_FullMethodName       = "/WsServer/Send"
)

// WsServerClient is the client API for WsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义通知服务
type WsServerClient interface {
	Preconnect(ctx context.Context, in *PreconnectRequest, opts ...grpc.CallOption) (*PreconnectResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type wsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewWsServerClient(cc grpc.ClientConnInterface) WsServerClient {
	return &wsServerClient{cc}
}

func (c *wsServerClient) Preconnect(ctx context.Context, in *PreconnectRequest, opts ...grpc.CallOption) (*PreconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreconnectResponse)
	err := c.cc.Invoke(ctx, WsServer_Preconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsServerClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, WsServer_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsServerServer is the server API for WsServer service.
// All implementations must embed UnimplementedWsServerServer
// for forward compatibility.
//
// 定义通知服务
type WsServerServer interface {
	Preconnect(context.Context, *PreconnectRequest) (*PreconnectResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedWsServerServer()
}

// UnimplementedWsServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWsServerServer struct{}

func (UnimplementedWsServerServer) Preconnect(context.Context, *PreconnectRequest) (*PreconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preconnect not implemented")
}
func (UnimplementedWsServerServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedWsServerServer) mustEmbedUnimplementedWsServerServer() {}
func (UnimplementedWsServerServer) testEmbeddedByValue()                  {}

// UnsafeWsServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsServerServer will
// result in compilation errors.
type UnsafeWsServerServer interface {
	mustEmbedUnimplementedWsServerServer()
}

func RegisterWsServerServer(s grpc.ServiceRegistrar, srv WsServerServer) {
	// If the following call pancis, it indicates UnimplementedWsServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WsServer_ServiceDesc, srv)
}

func _WsServer_Preconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServerServer).Preconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsServer_Preconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServerServer).Preconnect(ctx, req.(*PreconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsServer_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsServerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsServer_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsServerServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WsServer_ServiceDesc is the grpc.ServiceDesc for WsServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WsServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WsServer",
	HandlerType: (*WsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Preconnect",
			Handler:    _WsServer_Preconnect_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _WsServer_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wsserver.proto",
}
