// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative notify.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: wsserver.proto

package wsserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsServerStatus int32

const (
	WsServerStatus_WSSERVER_SUCCESS WsServerStatus = 0 // 发送成功
	WsServerStatus_WSSERVER_FAILED  WsServerStatus = 1 // 发送失败
)

// Enum value maps for WsServerStatus.
var (
	WsServerStatus_name = map[int32]string{
		0: "WSSERVER_SUCCESS",
		1: "WSSERVER_FAILED",
	}
	WsServerStatus_value = map[string]int32{
		"WSSERVER_SUCCESS": 0,
		"WSSERVER_FAILED":  1,
	}
)

func (x WsServerStatus) Enum() *WsServerStatus {
	p := new(WsServerStatus)
	*p = x
	return p
}

func (x WsServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wsserver_proto_enumTypes[0].Descriptor()
}

func (WsServerStatus) Type() protoreflect.EnumType {
	return &file_wsserver_proto_enumTypes[0]
}

func (x WsServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsServerStatus.Descriptor instead.
func (WsServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_wsserver_proto_rawDescGZIP(), []int{0}
}

// 获取wsid请求参数
type PreconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 业务系统用户登录Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreconnectRequest) Reset() {
	*x = PreconnectRequest{}
	mi := &file_wsserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconnectRequest) ProtoMessage() {}

func (x *PreconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wsserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconnectRequest.ProtoReflect.Descriptor instead.
func (*PreconnectRequest) Descriptor() ([]byte, []int) {
	return file_wsserver_proto_rawDescGZIP(), []int{0}
}

func (x *PreconnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取wsid响应参数
type PreconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WsServerStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=WsServerStatus" json:"status,omitempty"`
	Wsid          string                 `protobuf:"bytes,2,opt,name=wsid,proto3" json:"wsid,omitempty"`           // WS服务生成的唯一WebSocket连接ID
	WsAddr        string                 `protobuf:"bytes,3,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`       // WebSocket服务地址
	GrpcAddr      string                 `protobuf:"bytes,4,opt,name=grpcAddr,proto3" json:"grpcAddr,omitempty"`   // gRPC服务地址
	MachineId     string                 `protobuf:"bytes,5,opt,name=machineId,proto3" json:"machineId,omitempty"` // 机器ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreconnectResponse) Reset() {
	*x = PreconnectResponse{}
	mi := &file_wsserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreconnectResponse) ProtoMessage() {}

func (x *PreconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wsserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreconnectResponse.ProtoReflect.Descriptor instead.
func (*PreconnectResponse) Descriptor() ([]byte, []int) {
	return file_wsserver_proto_rawDescGZIP(), []int{1}
}

func (x *PreconnectResponse) GetStatus() WsServerStatus {
	if x != nil {
		return x.Status
	}
	return WsServerStatus_WSSERVER_SUCCESS
}

func (x *PreconnectResponse) GetWsid() string {
	if x != nil {
		return x.Wsid
	}
	return ""
}

func (x *PreconnectResponse) GetWsAddr() string {
	if x != nil {
		return x.WsAddr
	}
	return ""
}

func (x *PreconnectResponse) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *PreconnectResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

// 发送通知请求参数
type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wsid          []string               `protobuf:"bytes,1,rep,name=wsid,proto3" json:"wsid,omitempty"`             // 指定要发送的wsid数组
	SenderWsid    string                 `protobuf:"bytes,2,opt,name=senderWsid,proto3" json:"senderWsid,omitempty"` // 发送人的wsid
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`       // 发送的消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_wsserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wsserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_wsserver_proto_rawDescGZIP(), []int{2}
}

func (x *SendRequest) GetWsid() []string {
	if x != nil {
		return x.Wsid
	}
	return nil
}

func (x *SendRequest) GetSenderWsid() string {
	if x != nil {
		return x.SenderWsid
	}
	return ""
}

func (x *SendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送通知响应参数
type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WsServerStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=WsServerStatus" json:"status,omitempty"`
	OfflineWisd   []string               `protobuf:"bytes,2,rep,name=offlineWisd,proto3" json:"offlineWisd,omitempty"`   // 离线的目标对象的wsid数组
	SenderWsid    string                 `protobuf:"bytes,3,opt,name=senderWsid,proto3" json:"senderWsid,omitempty"`     // 发送人的wsid
	SenderStatus  string                 `protobuf:"bytes,4,opt,name=senderStatus,proto3" json:"senderStatus,omitempty"` // 1:在线 2:离线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_wsserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wsserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_wsserver_proto_rawDescGZIP(), []int{3}
}

func (x *SendResponse) GetStatus() WsServerStatus {
	if x != nil {
		return x.Status
	}
	return WsServerStatus_WSSERVER_SUCCESS
}

func (x *SendResponse) GetOfflineWisd() []string {
	if x != nil {
		return x.OfflineWisd
	}
	return nil
}

func (x *SendResponse) GetSenderWsid() string {
	if x != nil {
		return x.SenderWsid
	}
	return ""
}

func (x *SendResponse) GetSenderStatus() string {
	if x != nil {
		return x.SenderStatus
	}
	return ""
}

var File_wsserver_proto protoreflect.FileDescriptor

const file_wsserver_proto_rawDesc = "" +
	"\n" +
	"\x0ewsserver.proto\")\n" +
	"\x11PreconnectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa3\x01\n" +
	"\x12PreconnectResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.WsServerStatusR\x06status\x12\x12\n" +
	"\x04wsid\x18\x02 \x01(\tR\x04wsid\x12\x16\n" +
	"\x06wsAddr\x18\x03 \x01(\tR\x06wsAddr\x12\x1a\n" +
	"\bgrpcAddr\x18\x04 \x01(\tR\bgrpcAddr\x12\x1c\n" +
	"\tmachineId\x18\x05 \x01(\tR\tmachineId\"[\n" +
	"\vSendRequest\x12\x12\n" +
	"\x04wsid\x18\x01 \x03(\tR\x04wsid\x12\x1e\n" +
	"\n" +
	"senderWsid\x18\x02 \x01(\tR\n" +
	"senderWsid\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9d\x01\n" +
	"\fSendResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.WsServerStatusR\x06status\x12 \n" +
	"\vofflineWisd\x18\x02 \x03(\tR\vofflineWisd\x12\x1e\n" +
	"\n" +
	"senderWsid\x18\x03 \x01(\tR\n" +
	"senderWsid\x12\"\n" +
	"\fsenderStatus\x18\x04 \x01(\tR\fsenderStatus*;\n" +
	"\x0eWsServerStatus\x12\x14\n" +
	"\x10WSSERVER_SUCCESS\x10\x00\x12\x13\n" +
	"\x0fWSSERVER_FAILED\x10\x012j\n" +
	"\bWsServer\x127\n" +
	"\n" +
	"Preconnect\x12\x12.PreconnectRequest\x1a\x13.PreconnectResponse\"\x00\x12%\n" +
	"\x04Send\x12\f.SendRequest\x1a\r.SendResponse\"\x00B\fZ\n" +
	".;wsserverb\x06proto3"

var (
	file_wsserver_proto_rawDescOnce sync.Once
	file_wsserver_proto_rawDescData []byte
)

func file_wsserver_proto_rawDescGZIP() []byte {
	file_wsserver_proto_rawDescOnce.Do(func() {
		file_wsserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wsserver_proto_rawDesc), len(file_wsserver_proto_rawDesc)))
	})
	return file_wsserver_proto_rawDescData
}

var file_wsserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wsserver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wsserver_proto_goTypes = []any{
	(WsServerStatus)(0),        // 0: WsServerStatus
	(*PreconnectRequest)(nil),  // 1: PreconnectRequest
	(*PreconnectResponse)(nil), // 2: PreconnectResponse
	(*SendRequest)(nil),        // 3: SendRequest
	(*SendResponse)(nil),       // 4: SendResponse
}
var file_wsserver_proto_depIdxs = []int32{
	0, // 0: PreconnectResponse.status:type_name -> WsServerStatus
	0, // 1: SendResponse.status:type_name -> WsServerStatus
	1, // 2: WsServer.Preconnect:input_type -> PreconnectRequest
	3, // 3: WsServer.Send:input_type -> SendRequest
	2, // 4: WsServer.Preconnect:output_type -> PreconnectResponse
	4, // 5: WsServer.Send:output_type -> SendResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wsserver_proto_init() }
func file_wsserver_proto_init() {
	if File_wsserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wsserver_proto_rawDesc), len(file_wsserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wsserver_proto_goTypes,
		DependencyIndexes: file_wsserver_proto_depIdxs,
		EnumInfos:         file_wsserver_proto_enumTypes,
		MessageInfos:      file_wsserver_proto_msgTypes,
	}.Build()
	File_wsserver_proto = out.File
	file_wsserver_proto_goTypes = nil
	file_wsserver_proto_depIdxs = nil
}
