// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: callback.proto

package callback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackStatus int32

const (
	CallbackStatus_SUCCESS CallbackStatus = 0 // 发送成功
	CallbackStatus_FAILED  CallbackStatus = 1 // 发送失败
)

// Enum value maps for CallbackStatus.
var (
	CallbackStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	CallbackStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x CallbackStatus) Enum() *CallbackStatus {
	p := new(CallbackStatus)
	*p = x
	return p
}

func (x CallbackStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallbackStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_callback_proto_enumTypes[0].Descriptor()
}

func (CallbackStatus) Type() protoreflect.EnumType {
	return &file_callback_proto_enumTypes[0]
}

func (x CallbackStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallbackStatus.Descriptor instead.
func (CallbackStatus) EnumDescriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{0}
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wsid          string                 `protobuf:"bytes,1,opt,name=wsid,proto3" json:"wsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetWsid() string {
	if x != nil {
		return x.Wsid
	}
	return ""
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CallbackStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=CallbackStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetStatus() CallbackStatus {
	if x != nil {
		return x.Status
	}
	return CallbackStatus_SUCCESS
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wsid          string                 `protobuf:"bytes,1,opt,name=wsid,proto3" json:"wsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_callback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{2}
}

func (x *CloseRequest) GetWsid() string {
	if x != nil {
		return x.Wsid
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CallbackStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=CallbackStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_callback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_callback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_callback_proto_rawDescGZIP(), []int{3}
}

func (x *CloseResponse) GetStatus() CallbackStatus {
	if x != nil {
		return x.Status
	}
	return CallbackStatus_SUCCESS
}

var File_callback_proto protoreflect.FileDescriptor

const file_callback_proto_rawDesc = "" +
	"\n" +
	"\x0ecallback.proto\"!\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04wsid\x18\x01 \x01(\tR\x04wsid\"7\n" +
	"\fOpenResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.CallbackStatusR\x06status\"\"\n" +
	"\fCloseRequest\x12\x12\n" +
	"\x04wsid\x18\x01 \x01(\tR\x04wsid\"8\n" +
	"\rCloseResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.CallbackStatusR\x06status*)\n" +
	"\x0eCallbackStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012[\n" +
	"\bCallback\x12%\n" +
	"\x04Open\x12\f.OpenRequest\x1a\r.OpenResponse\"\x00\x12(\n" +
	"\x05Close\x12\r.CloseRequest\x1a\x0e.CloseResponse\"\x00B\fZ\n" +
	".;callbackb\x06proto3"

var (
	file_callback_proto_rawDescOnce sync.Once
	file_callback_proto_rawDescData []byte
)

func file_callback_proto_rawDescGZIP() []byte {
	file_callback_proto_rawDescOnce.Do(func() {
		file_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_callback_proto_rawDesc), len(file_callback_proto_rawDesc)))
	})
	return file_callback_proto_rawDescData
}

var file_callback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_callback_proto_goTypes = []any{
	(CallbackStatus)(0),   // 0: CallbackStatus
	(*OpenRequest)(nil),   // 1: OpenRequest
	(*OpenResponse)(nil),  // 2: OpenResponse
	(*CloseRequest)(nil),  // 3: CloseRequest
	(*CloseResponse)(nil), // 4: CloseResponse
}
var file_callback_proto_depIdxs = []int32{
	0, // 0: OpenResponse.status:type_name -> CallbackStatus
	0, // 1: CloseResponse.status:type_name -> CallbackStatus
	1, // 2: Callback.Open:input_type -> OpenRequest
	3, // 3: Callback.Close:input_type -> CloseRequest
	2, // 4: Callback.Open:output_type -> OpenResponse
	4, // 5: Callback.Close:output_type -> CloseResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_callback_proto_init() }
func file_callback_proto_init() {
	if File_callback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_callback_proto_rawDesc), len(file_callback_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_callback_proto_goTypes,
		DependencyIndexes: file_callback_proto_depIdxs,
		EnumInfos:         file_callback_proto_enumTypes,
		MessageInfos:      file_callback_proto_msgTypes,
	}.Build()
	File_callback_proto = out.File
	file_callback_proto_goTypes = nil
	file_callback_proto_depIdxs = nil
}
